#
#frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "activesupport"
gem "aubio", :git => "https://github.com/wstephenson/ruby-aubio.git"
gem "fast_osc"
gem "gettext"
gem "hamster"
gem "kramdown"
gem "memoist"
gem "multi_json"
gem "rubame"
gem "ruby-beautify"
#gem "coreaudio"
gem "rugged"
gem "sys-proctable"
gem "wavefile"
